title: Welcome To Homepage of Abhas
email: your-abhasgorain@gmail.com
description: >
  This is the first trial in creating my web page
baseurl: ""
url: "http://yourdomain.com"
github_username:  abhskg

markdown: kramdown

theme: jekyll-theme-cayman
